# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

tickethq: &tickethq
  adapter: mysql
  pool: 5
  timeout: 8000
  username: tickethq
  password: tickethq
  host: localhost

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  database: tickethq
  <<: *tickethq

production:
  database: tickethq
  <<: *tickethq